
spring:
  application:
    name: eureka-peer9000
  profiles: dev

server:
  port: 9000

eureka:
  instance:
    hostname: eureka-instance9000
    instance-id: eureka-instance9000
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:9000/eureka/,http://localhost:9001/eureka/,http://localhost:9002/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: true
    peer-eureka-nodes-update-interval-ms: 10000

